#connecting to server 
- name: ping the server
  hosts: web #connecting from another server and giving private ip in iventory file under web group
  tasks:
   - name: ping the server
     ansible.builtin.ping: #to connect to server


#to check output in prompt: ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 playbook.yaml