# to print from ansible 
- name: to print in ansible
  hosts: web
  tasks:
  - name: print the message
    ansible.builtin.debug: #to print in ansible 
     msg: "hi,hello from ansible"

#to check output in prompt: ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 print.yaml
