#calling vairables from 07.vairanles.yaml file

- name: vairables
  hosts: local
  connection: local
  vars_files: #to call from another vairable file
  - 07.vairables.yaml #vairable file
  tasks: 
  - name: print vairables
    vars:
    - topic: "ansible"
    ansible.builtin.debug:
      msg: "course is: {{ COURSE }}, duration of course is: {{ DURATION }}, days is: {{ DAYS }}, timings of course is: {{ Timings }},
        topics covered till now is: {{ past_topics }} and topic now is {{ topic }}"

# in prompt: ansible-playbook -i inventory.ini 08.call-vairables.yaml
#"msg": "course is: DevOps with AWS, duration of course is: 4 months, days is: 5 days, timings of course is: 8 pm -10 pm , topics covered till now is: linux, shell and topic now is ansible"
