#giving input from command prompt vairables

- name: prompt
  hosts: local
  connection: local
  vars_prompt: #to give input through command prompt
  - name: username
    prompt: "please enter the username"
    private: false #visible the entered input in screen

  - name: password
    prompt: "please enter the password"
    private: true #not visible the entered input in screen

  tasks:
  - name: print the username and password
    ansible.builtin.debug:
     msg: "username is {{ username }}, password is {{ password }}"
   
# in prompt: ansible-playbook -i inventory.ini 09.prompt-vairables.yaml
#please enter the username: honey
#please enter the password:
#"msg": "username is honey, password is kunamneni" here we printed the password that is why it is showing

  