#to learn conditions in ansible

- name: conditions in ansible
  hosts: local #run ansible locally 
  connection: local #need to use SSH to connect to server
  vars:
   course: DevOps
   is_live: true
  tasks:
  - name: check condition
    ansible.builtin.debug:
      msg: "is the {{ course }} class is live everyday?"
    when: is_live #checking the condition if ture will execute above msg otherwise it terminates the script

#in prompt: ansible-playbook -i inventory.ini 14.conditions.yaml
#is_live:true here the given condtion is true so we got ouptut as below
#"msg": "is the DevOps class is live everyday?"
#if we give is_live:false and run the playbook then we get output as skipping