# to learn conditions in yaml

- name: check number less than 10 or not
  hosts: local
  connection: local
  vars:
   number: 6
  tasks:
  - name: check condition
    ansible.builtin.debug:
       msg: "given number is greather than 5"
    when: number > 5

  - name: check condition
    ansible.builtin.debug:
       msg: "given number is less than 5"
    when: number <= 5



#while giving when condition we don't use any type of braces that is fixed syntax
#in prompt:ansible-playbook -i inventory.ini 15.conditions.yaml
#ok: [localhost] => {
    #"msg": "given number is greather than 5"
#if i run the command prompt as  ansible-playbook -i inventory.ini -e '{"number":3}' 15.conditions.yaml
#then i get otutput as  msg: "given number is less than 5" because here command prompt -e vars overrides the play level vars
