#to check whats inside gathering facts statement in ansible

- name: gathering facts
  hosts: local
  connection: local
  gather_facts: yes
  tasks:
  - name: print gathering facts
    ansible.builtin.debug:
     msg: "{{ ansible_facts }}"


#Ansible factsThis prints all system facts collected by Ansible, such as OS type,IP address,hostname,CPU,memory,disk information
