#to check whats inside gathering facts statement in ansible

- name: gathering facts
  hosts: local
  connection: local
  tasks:
  - name: print gathering facts
    ansible.builtin.debug:
     msg: "{{ ansible_facts }}"
  
  - name: check Redhat or not
    ansible.builtin.debug:
      msg: "the package manager is Redhat"
    when: ansible_facts.os_family == "RedHat"

  - name: check Debain or not
    ansible.builtin.debug:
      msg: "the package manager is Debain"
    when: ansible_facts.os_family == "Debain"


#Ansible factsThis prints all system facts collected by Ansible, such as OS type,IP address,hostname,CPU,memory,disk information
