192.45.25.06 --->stand alone seevers can be given like this

[frontend] -->this is called group in this we can keep all frontend servers
192.67.89.44
192.67.89.46

[backend]---> in this group we can keep all backend servers
156.45.78.99
156.45.78.97
156.45.78.90
156.45.78.92
156.45.78.93

[database]-->in this group we can keep all database servers
98.45.67.86
98.45.67.83
98.45.67.80
98.45.67.8

[roboshop:children]---> in roboshop group contains other groups as its members.So instead of listing servers directly, you add groups inside this parent group.
frontend
backend
database